'use client';

import { useEffect, useState } from 'react';
import TelemetryCard from '@/components/ui/TelemetryCard';
import { Activity, Users, Zap, TrendingUp, AlertCircle, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';

// API Response shapes
interface AdminData {
  funnel: { visits: number; starts: number; verified: number; activated: number };
  channelStats: Record<string, number>;
}
interface CohortData {
  metrics: Record<string, string>;
  dateCohorts: Array<{ date: string; value: number }>;
  sourceCohorts: Array<{ name: string; value: number }>;
}

export default function AdminCommandCenter() {
  const [data, setData] = useState<AdminData | null>(null);
  const [cohortData, setCohortData] = useState<CohortData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetch('/api/analytics/funnel').then(res => res.json()),
      fetch('/api/analytics/cohorts').then(res => res.json())
    ])
    .then(([funnelJson, cohortJson]) => {
      if (funnelJson.success) setData(funnelJson.data);
      if (cohortJson.success) setCohortData(cohortJson.data);
      setLoading(false);
    })
    .catch(console.error);
  }, []);

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="flex items-center gap-3 text-zinc-500 font-mono text-sm">
          <RefreshCw className="w-4 h-4 animate-spin" /> Fetching telemetry...
        </div>
      </div>
    );
  }

  if (!data || !cohortData) {
    return (
      <div className="flex-1 flex items-center justify-center p-8 text-rose-400 font-mono text-sm">
        <AlertCircle className="w-4 h-4 mr-2 inline" /> Error loading telemetry data
      </div>
    );
  }

  // Derived metrics
  const totalReg = data.funnel.verified;
  const target = 500;
  const referralRate = totalReg > 0 ? ((data.funnel.activated / totalReg) * 100).toFixed(1) : "0.0";
  const cvr = data.funnel.starts > 0 ? ((totalReg / data.funnel.starts) * 100).toFixed(1) : "0.0";

  return (
    <div className="flex-1 p-6 lg:p-10 max-w-7xl mx-auto w-full text-slate-200">
      <div className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-semibold text-white tracking-tight mb-1">Growth Telemetry</h1>
          <p className="text-sm text-zinc-500 font-medium">Real-time tracking for Campaign: AI Workshop</p>
        </div>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <TelemetryCard 
          title="Total Registrations" 
          value={totalReg} 
          delta={24} deltaType="positive"
          subtitle={`Target: ${target} (${((totalReg/target)*100).toFixed(0)}%)`}
          icon={<Users className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Referred Registrations" 
          value={data.funnel.activated} 
          delta={18} deltaType="positive"
          subtitle="Generated by student network"
          icon={<Zap className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Conversion Rate (CVR)" 
          value={`${cvr}%`} 
          delta={-2.1} deltaType="negative"
          subtitle="Signups to Verified"
          icon={<TrendingUp className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Fraud Risk" 
          value="LOW" 
          subtitle="Anomalies detected: 0"
          icon={<AlertCircle className="w-4 h-4" />}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Funnel */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6 lg:col-span-2">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6 flex items-center gap-2">
            <Activity className="w-4 h-4 text-blue-400" /> Primary Funnel
          </h3>
          <div className="space-y-6">
            {[
              { label: 'Form Starts', val: data.funnel.starts, max: Math.max(data.funnel.starts, 1) },
              { label: 'Verified Registrations', val: data.funnel.verified, max: Math.max(data.funnel.starts, 1) },
              { label: 'Active Referrers', val: data.funnel.activated, max: Math.max(data.funnel.starts, 1) },
            ].map((step, idx) => (
              <div key={idx} className="relative">
                <div className="flex justify-between text-xs font-medium mb-2">
                  <span className="text-zinc-400">{step.label}</span>
                  <span className="text-white">{step.val}</span>
                </div>
                <div className="h-2 w-full bg-[#1a1a1a] rounded-full overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${(step.val / step.max) * 100}%` }}
                    transition={{ duration: 1, delay: idx * 0.1, ease: "easeOut" }}
                    className="h-full bg-blue-500 rounded-full"
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Channel Attribution */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6">Channel Performance</h3>
          <div className="space-y-4">
            {Object.entries(data.channelStats).length > 0 ? (
              Object.entries(data.channelStats).map(([channel, count], i) => (
                <div key={channel} className="flex items-center justify-between group">
                  <span className="text-sm text-zinc-400 capitalize flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${i === 0 ? 'bg-blue-400' : i === 1 ? 'bg-emerald-400' : 'bg-zinc-600'}`} />
                    {channel || 'Unknown'}
                  </span>
                  <span className="text-sm font-medium text-white group-hover:text-blue-400 transition-colors">{count}</span>
                </div>
              ))
            ) : (
              <div className="text-xs text-zinc-600 font-mono text-center py-4">No channel data</div>
            )}
          </div>
        </div>

        {/* Character Funnel */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6">Explorer Onboarding</h3>
          <div className="space-y-4">
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Account Created</span>
               <span className="text-zinc-200">1,245</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-full h-1.5 mb-4">
               <div className="bg-blue-500 h-1.5 rounded-full" style={{ width: '100%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Character Started</span>
               <span className="text-zinc-200">1,210 (97%)</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-full h-1.5 mb-4">
               <div className="bg-blue-500 h-1.5 rounded-full" style={{ width: '97%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Character Completed</span>
               <span className="text-zinc-200">1,180 (94%)</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-full h-1.5 mb-4">
               <div className="bg-emerald-500 h-1.5 rounded-full" style={{ width: '94%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Time to First Value</span>
               <span className="text-zinc-200">~2.4 mins</span>
             </div>
          </div>
        </div>

      </div>
    </div>
  );
}
