'use client';

import { useEffect, useState } from 'react';
import TelemetryCard from '@/components/ui/TelemetryCard';
import { Activity, Users, Zap, TrendingUp, AlertCircle, RefreshCw } from 'lucide-react';
import { motion } from 'framer-motion';

// API Response shapes
interface AdminData {
  funnel: { visits: number; starts: number; verified: number; activated: number };
  channelStats: Record<string, number>;
}
interface CohortData {
  metrics: Record<string, string>;
  dateCohorts: Array<{ date: string; value: number }>;
  sourceCohorts: Array<{ name: string; value: number }>;
}

export default function AdminCommandCenter() {
  const [data, setData] = useState<AdminData | null>(null);
  const [cohortData, setCohortData] = useState<CohortData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      fetch('/api/analytics/funnel').then(res => res.json()),
      fetch('/api/analytics/cohorts').then(res => res.json())
    ])
    .then(([funnelJson, cohortJson]) => {
      if (funnelJson.success) setData(funnelJson.data);
      if (cohortJson.success) setCohortData(cohortJson.data);
      setLoading(false);
    })
    .catch(err => {
      console.error(err);
      setLoading(false);
    });
  }, []);

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="flex items-center gap-3 text-zinc-500 font-mono text-sm">
          <RefreshCw className="w-4 h-4 animate-spin" /> Fetching telemetry...
        </div>
      </div>
    );
  }

  if (!data || !cohortData) {
    return (
      <div className="flex-1 flex items-center justify-center p-8 text-rose-400 font-mono text-sm">
        <AlertCircle className="w-4 h-4 mr-2 inline" /> Error loading telemetry data
      </div>
    );
  }

  // Derived metrics
  const totalReg = data.funnel.verified;
  const target = 500;
  const referralRate = totalReg > 0 ? ((data.funnel.activated / totalReg) * 100).toFixed(1) : "0.0";
  const cvr = data.funnel.starts > 0 ? ((totalReg / data.funnel.starts) * 100).toFixed(1) : "0.0";

  return (
    <div className="flex-1 p-6 lg:p-10 max-w-7xl mx-auto w-full text-slate-200">
      <div className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-semibold text-white tracking-tight mb-1">Growth Telemetry</h1>
          <p className="text-sm text-zinc-500 font-medium">Real-time tracking for Campaign: AI Workshop</p>
        </div>
      </div>

      {/* KPI Row */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <TelemetryCard 
          title="Total Registrations" 
          value={totalReg} 
          delta={24} deltaType="positive"
          subtitle={`Target: ${target} (${((totalReg/target)*100).toFixed(0)}%)`}
          icon={<Users className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Referred Registrations" 
          value={data.funnel.activated} 
          delta={18} deltaType="positive"
          subtitle="Generated by student network"
          icon={<Zap className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Conversion Rate (CVR)" 
          value={`${cvr}%`} 
          delta={-2.1} deltaType="negative"
          subtitle="Signups to Verified"
          icon={<TrendingUp className="w-4 h-4" />}
        />
        <TelemetryCard 
          title="Fraud Risk" 
          value="LOW" 
          subtitle="Anomalies detected: 0"
          icon={<AlertCircle className="w-4 h-4" />}
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Funnel */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6 lg:col-span-2">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6 flex items-center gap-2">
            <Activity className="w-4 h-4 text-blue-400" /> Primary Funnel
          </h3>
          <div className="space-y-6">
            {[
              { label: 'Form Starts', val: data.funnel.starts, max: Math.max(data.funnel.starts, 1) },
              { label: 'Verified Registrations', val: data.funnel.verified, max: Math.max(data.funnel.starts, 1) },
              { label: 'Active Referrers', val: data.funnel.activated, max: Math.max(data.funnel.starts, 1) },
            ].map((step, idx) => (
              <div key={idx} className="relative">
                <div className="flex justify-between text-xs font-medium mb-2">
                  <span className="text-zinc-400">{step.label}</span>
                  <span className="text-white">{step.val}</span>
                </div>
                <div className="h-2 w-full bg-[#1a1a1a] rounded-none overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${(step.val / step.max) * 100}%` }}
                    transition={{ duration: 1, delay: idx * 0.1, ease: "easeOut" }}
                    className="h-full bg-blue-500 rounded-none"
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Channel Attribution */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6">Channel Performance</h3>
          <div className="space-y-4">
            {Object.entries(data.channelStats).length > 0 ? (
              Object.entries(data.channelStats).map(([channel, count], i) => (
                <div key={channel} className="flex items-center justify-between group">
                  <span className="text-sm text-zinc-400 capitalize flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-none ${i === 0 ? 'bg-blue-400' : i === 1 ? 'bg-emerald-400' : 'bg-zinc-600'}`} />
                    {channel || 'Unknown'}
                  </span>
                  <span className="text-sm font-medium text-white group-hover:text-blue-400 transition-colors">{count}</span>
                </div>
              ))
            ) : (
              <div className="text-xs text-zinc-600 font-mono text-center py-4">No channel data</div>
            )}
          </div>
        </div>

        {/* Character Funnel */}
        <div className="bg-[#111] border border-white/10 rounded-xl p-6">
          <h3 className="text-sm font-semibold text-zinc-200 mb-6">Explorer Onboarding</h3>
          <div className="space-y-4">
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Account Created</span>
               <span className="text-zinc-200">1,245</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-none h-1.5 mb-4">
               <div className="bg-blue-500 h-1.5 rounded-none" style={{ width: '100%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Character Started</span>
               <span className="text-zinc-200">1,210 (97%)</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-none h-1.5 mb-4">
               <div className="bg-blue-500 h-1.5 rounded-none" style={{ width: '97%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Character Completed</span>
               <span className="text-zinc-200">1,180 (94%)</span>
             </div>
             <div className="w-full bg-zinc-800 rounded-none h-1.5 mb-4">
               <div className="bg-emerald-500 h-1.5 rounded-none" style={{ width: '94%' }}></div>
             </div>
             
             <div className="flex justify-between text-xs mb-1">
               <span className="text-zinc-400">Time to First Value</span>
               <span className="text-zinc-200">~2.4 mins</span>
             </div>
          </div>
        </div>

        {/* Campaign Controls */}
        <div className="col-span-1 lg:col-span-3 bg-[#111] border border-red-900/50 rounded-xl p-6 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-red-500/5 blur-[100px] rounded-none pointer-events-none" />
          
          <div className="flex justify-between items-start mb-6">
            <div>
              <h3 className="text-sm font-semibold text-zinc-200 flex items-center gap-2">
                <span className="w-2 h-2 rounded-none bg-red-500 animate-pulse" />
                Live Campaign Operations
              </h3>
              <p className="text-xs text-zinc-500 mt-1">Global overrides and communication triggers.</p>
            </div>
            <div className="text-xs font-mono text-red-500 border border-red-900/50 bg-red-950/30 px-2 py-1 rounded">
              RESTRICTED ACCESS
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="border border-white/5 bg-[#0a0a0a] p-4 rounded-lg">
              <div className="text-sm font-medium text-zinc-300 mb-1">Workshop Status</div>
              <div className="text-xs text-zinc-500 mb-4">Overrides the countdown timer across all clients.</div>
              <div className="flex gap-2">
                <button className="flex-1 bg-zinc-800 hover:bg-zinc-700 text-xs py-2 rounded text-zinc-300 transition-colors">STANDBY</button>
                <button className="flex-1 bg-blue-600 hover:bg-blue-500 text-xs py-2 rounded text-white transition-colors">GO LIVE</button>
              </div>
            </div>

            <div className="border border-white/5 bg-[#0a0a0a] p-4 rounded-lg">
              <div className="text-sm font-medium text-zinc-300 mb-1">Registration Gate</div>
              <div className="text-xs text-zinc-500 mb-4">Force active waitlist mode even if capacity &lt; 500.</div>
              <div className="flex gap-2">
                <button className="flex-1 bg-emerald-900/30 border border-emerald-900 text-emerald-500 text-xs py-2 rounded transition-colors">OPEN</button>
                <button className="flex-1 bg-zinc-800 hover:bg-zinc-700 text-xs py-2 rounded text-zinc-300 transition-colors">WAITLIST</button>
              </div>
            </div>

            <div className="border border-white/5 bg-[#0a0a0a] p-4 rounded-lg">
              <div className="text-sm font-medium text-zinc-300 mb-1">Mass Comms (WhatsApp)</div>
              <div className="text-xs text-zinc-500 mb-4">Trigger broadcast to all 380+ registered students.</div>
              <button className="w-full bg-zinc-800 hover:bg-zinc-700 text-xs py-2 rounded text-zinc-300 transition-colors border border-zinc-700 flex items-center justify-center gap-2">
                <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" /></svg>
                SEND &quot;-1HR REMINDER&quot;
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}

